### ISSUE TITLE
[question]:Parameters doubts 

### ISSUE THREAD

**Issue by miguelcositis** [jsten07/cms_routing#4]
@PondiB @tnier01 @jsten07 @njakuschona 

I would like to ask about what was said in this other issue #3 , the reason for these constants in "prediction.py " at advanced_scripts folder( line 188~197)

I would also like to know the reason for the fuelArray constants in "calculate_objectives.py " at advanced_scripts (line 6):

```
# Array of fuel cost per hour for the different engine powers [0.6, 0.7, 0.8]
fuelArray=[152*33200, 154*33200, 156*33200]
```

Thank you very much in advance, amazing work!

**Comment by njakuschona** [comment]
Hello @miguelcha20 ,
i answered the first two questions in #3. Here now some more information about the fuelArray constants. These constants were retrieved from this paper https://www.wingd.com/en/documents/general/papers/engine-selection-for-very-large-container-vessels.pdf/ Figure 24. Meaning for a engine power of 60% it needs 152 g/kwh, for 80% 156 g/kwh. The values then were calculated for an example engine, which needs 33200 kw. 
I hope this helps you out. Feel free to contact us if you have any further questions.
